format = """
[ ](fg:#00BFFF)\
$directory\
[ ](fg:#00BFFF bg:#1E90FF)\
[](fg:#1E90FF bg:#1E90FF)\
$git_branch\
[](fg:#1E90FF bg:#836FFF)\
[](fg:#836FFF bg:#836FFF)\
$git_status\
[ ](fg:#836FFF)\
"""

command_timeout = 5000
add_newline = true

[directory]
style = "bg:#00BFFF"
format = '[$path]($style)'

[git_branch]
style = "bg:#23329A"
format = '[$branch (🌱$remote_branch)]($style)'
always_show_remote = true

[git_status]
style = "bg:#33658A"
format = '[$all_status$ahead_behind ]($style)'



