format = """
[ ](fg:#23329A)\
$git_branch\
[ ](fg:#23329A bg:#33658A)\
$git_status\
[ ](fg:#33658A)\
"""
command_timeout = 5000

[git_branch]
style = "bg:#23329A"
format = '[$branch (🌱$remote_branch)]($style)'
always_show_remote = true

[git_status]
style = "bg:#33658A"
format = '[$all_status$ahead_behind ]($style)'

